---
# This workflow will run periodically to check for new releases of prometheus
# and create pr to update the version when available

name: Update

on:
  schedule:
    - cron: '23 7 * * *'
  workflow_dispatch:
jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Version of Prometheus
        run: |
          set -e
          current=$(grep -oP '(?<=version_num=").*(?=")' install_prometheus.sh)
          latest_json=$(curl -s -XGET https://api.github.com/repos/prometheus/prometheus/releases/latest)
          latest=$(echo $latest_json | jq .tag_name | grep -oP '(?<="v).*(?=")')
          html_url=$(echo $latest_json | jq .html_url | tr -d '"')
          echo "CURRENT_VERSION=$current" >> $GITHUB_ENV
          echo "LATEST_VERSION=$latest" >> $GITHUB_ENV
          echo "HTML_URL=$html_url" >> $GITHUB_ENV
          sed -i '5s/.*/version_num="'$latest'"/' install_prometheus.sh
        working-directory: ./prometheus
      
      - name: Create PR
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          title: Bump Prometheus version from ${{ env.CURRENT_VERSION }} -> ${{ env.LATEST_VERSION }}
          body: '[Prometheus ${{env.LATEST_VERSION}} release](${{env.HTML_URL}})'
          commit-message: bump Prometheus version to ${{ env.LATEST_VERSION }}
          branch: bump-prometheus-version
          reviewers: |
            folksgl
            shumatepf
